const skillsData = [
  {
    id: "sk-1",
    name: "Navegacion Web",
    description:
      "Permite visitar sitios, extraer datos y navegar flujos web con reglas definidas.",
    useCases:
      "Monitoreo de precios, verificacion de informacion publica y captura de formularios.",
    price: 20,
    agentsCount: 7,
  },
  {
    id: "sk-2",
    name: "Gestion de Calendario",
    description:
      "Organiza eventos, detecta conflictos y coordina agendas entre equipos.",
    useCases:
      "Programacion de reuniones, recordatorios automaticos y replanificacion.",
    price: 10,
    agentsCount: 9,
  },
  {
    id: "sk-3",
    name: "Sincronizacion CRM",
    description:
      "Sincroniza contactos, oportunidades y estados entre plataformas de ventas.",
    useCases:
      "Actualizacion de leads, registro de interacciones y unificacion de datos.",
    price: 18,
    agentsCount: 6,
  },
  {
    id: "sk-4",
    name: "Redaccion de Emails",
    description:
      "Genera correos con tono configurable y plantillas para distintos contextos.",
    useCases:
      "Respuestas a clientes, seguimiento comercial y comunicados internos.",
    price: 12,
    agentsCount: 8,
  },
  {
    id: "sk-5",
    name: "Analisis Documental",
    description:
      "Procesa documentos extensos para resumir, clasificar y detectar patrones.",
    useCases: "Revision de contratos, reportes de auditoria y compliance.",
    price: 15,
    agentsCount: 5,
  },
  {
    id: "sk-6",
    name: "Calificacion de Leads",
    description:
      "Asigna puntajes de conversion en base a comportamiento y datos historicos.",
    useCases: "Priorizacion de prospectos y optimizacion de embudos.",
    price: 14,
    agentsCount: 7,
  },
  {
    id: "sk-7",
    name: "Extraccion de Datos",
    description:
      "Extrae entidades clave de texto, PDF y fuentes semiestructuradas.",
    useCases: "Carga de datos en ERP y normalizacion de entradas.",
    price: 16,
    agentsCount: 4,
  },
  {
    id: "sk-8",
    name: "Reporting",
    description:
      "Construye reportes ejecutivos y operativos con indicadores de negocio.",
    useCases:
      "Tableros semanales, reportes de rendimiento y alertas de desviacion.",
    price: 11,
    agentsCount: 10,
  },
];

const usersData = [
  {
    id: "us-1",
    name: "Laura Gomez",
    email: "laura@novatek.io",
    company: "NovaTek",
    plan: "Enterprise",
    status: "Activo",
    registerDate: "2025-11-02",
    lastAccess: "2026-06-17 10:14",
    agentsAssociated: 14,
  },
  {
    id: "us-2",
    name: "Carlos Mendez",
    email: "carlos@velocorp.com",
    company: "VeloCorp",
    plan: "Pro",
    status: "Pendiente",
    registerDate: "2026-01-15",
    lastAccess: "2026-06-16 16:55",
    agentsAssociated: 5,
  },
  {
    id: "us-3",
    name: "Sofia Ruiz",
    email: "sofia@altavia.co",
    company: "Altavia",
    plan: "Starter",
    status: "Suspendido",
    registerDate: "2025-08-09",
    lastAccess: "2026-06-10 08:21",
    agentsAssociated: 2,
  },
  {
    id: "us-4",
    name: "Martin Perez",
    email: "martin@lumen.ai",
    company: "Lumen AI",
    plan: "Enterprise",
    status: "Activo",
    registerDate: "2024-12-19",
    lastAccess: "2026-06-17 18:03",
    agentsAssociated: 21,
  },
  {
    id: "us-5",
    name: "Valentina Diaz",
    email: "valentina@orbis.tech",
    company: "Orbis Tech",
    plan: "Pro",
    status: "Activo",
    registerDate: "2026-03-01",
    lastAccess: "2026-06-17 09:44",
    agentsAssociated: 8,
  },
  {
    id: "us-6",
    name: "Diego Paredes",
    email: "diego@marketa.io",
    company: "Marketa",
    plan: "Starter",
    status: "Pendiente",
    registerDate: "2026-04-12",
    lastAccess: "2026-06-14 14:12",
    agentsAssociated: 3,
  },
  {
    id: "us-7",
    name: "Camila Torres",
    email: "camila@innova.com",
    company: "Innova",
    plan: "Enterprise",
    status: "Activo",
    registerDate: "2025-05-30",
    lastAccess: "2026-06-17 11:28",
    agentsAssociated: 17,
  },
  {
    id: "us-8",
    name: "Andres Molina",
    email: "andres@futura.net",
    company: "Futura",
    plan: "Pro",
    status: "Suspendido",
    registerDate: "2025-09-04",
    lastAccess: "2026-06-08 19:02",
    agentsAssociated: 6,
  },
];

const agentsData = [
  {
    id: "ag-1",
    name: "Atlas Support",
    owner: "Laura Gomez",
    status: "Activo",
    systemPrompt:
      "Eres un agente de soporte B2B. Responde con claridad, clasifica prioridad y propone proximo paso accionable.",
    skills: ["sk-1", "sk-4", "sk-8"],
  },
  {
    id: "ag-2",
    name: "Mercury Sales",
    owner: "Carlos Mendez",
    status: "Inactivo",
    systemPrompt:
      "Eres un agente comercial. Detecta intencion de compra y sugiere acciones de seguimiento por etapa.",
    skills: ["sk-3", "sk-6", "sk-8"],
  },
  {
    id: "ag-3",
    name: "Nexus Compliance",
    owner: "Sofia Ruiz",
    status: "Fallando",
    systemPrompt:
      "Analiza documentos y marca riesgos regulatorios con evidencia trazable.",
    skills: ["sk-5", "sk-7"],
  },
  {
    id: "ag-4",
    name: "Pulse Ops",
    owner: "Martin Perez",
    status: "Activo",
    systemPrompt:
      "Monitorea operaciones, consolida eventos y dispara alertas preventivas.",
    skills: ["sk-8", "sk-7", "sk-1"],
  },
  {
    id: "ag-5",
    name: "Orbit Planner",
    owner: "Valentina Diaz",
    status: "Activo",
    systemPrompt:
      "Gestiona agenda ejecutiva, evita conflictos y prepara resumenes previos.",
    skills: ["sk-2", "sk-4"],
  },
  {
    id: "ag-6",
    name: "Scout Leads",
    owner: "Diego Paredes",
    status: "Inactivo",
    systemPrompt:
      "Evalua leads y prioriza aquellos con mayor probabilidad de conversion.",
    skills: ["sk-6", "sk-3"],
  },
  {
    id: "ag-7",
    name: "PaperTrail",
    owner: "Camila Torres",
    status: "Activo",
    systemPrompt:
      "Resume contratos y genera checklist de validaciones antes de firma.",
    skills: ["sk-5", "sk-8"],
  },
  {
    id: "ag-8",
    name: "Harbor Inbox",
    owner: "Andres Molina",
    status: "Fallando",
    systemPrompt:
      "Redacta respuestas de email y organiza bandejas por prioridad operativa.",
    skills: ["sk-4", "sk-2", "sk-8"],
  },
  {
    id: "ag-9",
    name: "Signal Miner",
    owner: "Laura Gomez",
    status: "Activo",
    systemPrompt:
      "Extrae datos de documentos no estructurados y produce salidas normalizadas.",
    skills: ["sk-7", "sk-1"],
  },
  {
    id: "ag-10",
    name: "Ledger Eye",
    owner: "Martin Perez",
    status: "Activo",
    systemPrompt:
      "Audita transacciones y reporta anomalias con nivel de severidad y contexto.",
    skills: ["sk-5", "sk-8", "sk-6"],
  },
];

const contractsData = [
  {
    id: "ct-1",
    client: "NovaTek",
    agentId: "ag-1",
    skills: ["sk-1", "sk-4", "sk-8"],
    startDate: "2026-01-05",
    endDate: "2026-12-31",
  },
  {
    id: "ct-2",
    client: "VeloCorp",
    agentId: "ag-2",
    skills: ["sk-3", "sk-6", "sk-8"],
    startDate: "2026-02-12",
    endDate: "2026-11-30",
  },
  {
    id: "ct-3",
    client: "Altavia",
    agentId: "ag-3",
    skills: ["sk-5", "sk-7"],
    startDate: "2026-01-21",
    endDate: "2026-10-15",
  },
  {
    id: "ct-4",
    client: "Lumen AI",
    agentId: "ag-4",
    skills: ["sk-8", "sk-7", "sk-1"],
    startDate: "2026-03-03",
    endDate: "2026-12-01",
  },
  {
    id: "ct-5",
    client: "Orbis Tech",
    agentId: "ag-5",
    skills: ["sk-2", "sk-4"],
    startDate: "2026-04-18",
    endDate: "2027-04-17",
  },
  {
    id: "ct-6",
    client: "Marketa",
    agentId: "ag-6",
    skills: ["sk-6", "sk-3"],
    startDate: "2026-01-09",
    endDate: "2026-09-30",
  },
  {
    id: "ct-7",
    client: "Innova",
    agentId: "ag-7",
    skills: ["sk-5", "sk-8"],
    startDate: "2026-02-01",
    endDate: "2026-12-15",
  },
  {
    id: "ct-8",
    client: "Futura",
    agentId: "ag-8",
    skills: ["sk-4", "sk-2", "sk-8"],
    startDate: "2026-03-17",
    endDate: "2026-11-17",
  },
  {
    id: "ct-9",
    client: "BlueRail",
    agentId: "ag-9",
    skills: ["sk-7", "sk-1"],
    startDate: "2026-04-02",
    endDate: "2026-12-02",
  },
  {
    id: "ct-10",
    client: "ZenCore",
    agentId: "ag-10",
    skills: ["sk-5", "sk-8", "sk-6"],
    startDate: "2026-05-06",
    endDate: "2027-05-05",
  },
];

const errorsData = [
  {
    id: "er-1",
    dateTime: "2026-06-18 08:12",
    agentId: "ag-3",
    severity: "CRITICAL",
    summary: "Fallo de autenticacion con proveedor documental.",
    message: "Token invalido en integracion con almacenamiento documental.",
    stackTrace:
      "AuthError: invalid token\\n at DocumentConnector.login (connector.js:91)\\n at async runTask (runner.js:34)",
    metadata: "tenant=altavia; region=us-east-1; retry=0",
  },
  {
    id: "er-2",
    dateTime: "2026-06-18 08:33",
    agentId: "ag-8",
    severity: "ERROR",
    summary: "Timeout en generacion de respuesta.",
    message: "Tiempo maximo excedido al contactar modelo de redaccion.",
    stackTrace:
      "TimeoutError: request exceeded 6000ms\\n at sendPrompt (llm-client.js:122)",
    metadata: "tenant=futura; queue=email-high",
  },
  {
    id: "er-3",
    dateTime: "2026-06-18 09:04",
    agentId: "ag-2",
    severity: "WARNING",
    summary: "CRM respondio con campos incompletos.",
    message: "Se recibieron registros sin campo de etapa comercial.",
    stackTrace:
      "ValidationWarning: missing stage\\n at normalizeLead (crm.js:58)",
    metadata: "tenant=velocorp; importBatch=781",
  },
  {
    id: "er-4",
    dateTime: "2026-06-18 09:28",
    agentId: "ag-4",
    severity: "INFO",
    summary: "Reintento exitoso de tarea de monitoreo.",
    message: "El segundo intento completo la tarea sin errores.",
    stackTrace: "Info: retry succeeded\\n at scheduleJob (jobs.js:205)",
    metadata: "tenant=lumen; retry=1",
  },
  {
    id: "er-5",
    dateTime: "2026-06-18 09:42",
    agentId: "ag-3",
    severity: "ERROR",
    summary: "Documento no legible por formato no soportado.",
    message: "El parser no reconoce extension .odt protegida.",
    stackTrace: "ParseError: unsupported format\\n at parseFile (parser.js:17)",
    metadata: "tenant=altavia; file=contrato-77.odt",
  },
  {
    id: "er-6",
    dateTime: "2026-06-18 10:06",
    agentId: "ag-1",
    severity: "WARNING",
    summary: "Intento de scraping bloqueado por captcha.",
    message: "La pagina objetivo solicito verificacion manual.",
    stackTrace:
      "CaptchaBlock: interaction required\\n at navigateSite (web.js:301)",
    metadata: "tenant=novatek; url=example.com/pricing",
  },
  {
    id: "er-7",
    dateTime: "2026-06-18 10:19",
    agentId: "ag-7",
    severity: "INFO",
    summary: "Actualizacion de reglas aplicada.",
    message: "Se cargaron nuevas reglas de compliance desde plantilla.",
    stackTrace: "Info: rules refresh done\\n at reloadRules (rules.js:73)",
    metadata: "tenant=innova; version=2026.06.18",
  },
  {
    id: "er-8",
    dateTime: "2026-06-18 10:45",
    agentId: "ag-9",
    severity: "ERROR",
    summary: "Fallo de OCR en documento escaneado.",
    message: "No se pudo extraer texto util de imagen borrosa.",
    stackTrace: "OcrError: low confidence\\n at readImage (ocr.js:144)",
    metadata: "tenant=bluerail; confidence=0.31",
  },
  {
    id: "er-9",
    dateTime: "2026-06-18 11:02",
    agentId: "ag-8",
    severity: "CRITICAL",
    summary: "Servicio de correo externo no disponible.",
    message: "SMTP provider devolvio 503 por mantenimiento.",
    stackTrace: "ServiceUnavailable: smtp 503\\n at sendEmail (smtp.js:66)",
    metadata: "tenant=futura; provider=mailstream",
  },
  {
    id: "er-10",
    dateTime: "2026-06-18 11:20",
    agentId: "ag-6",
    severity: "INFO",
    summary: "Se recalculo score de leads con exito.",
    message: "Modelo de scoring actualizado y aplicado a lote diario.",
    stackTrace: "Info: scoring batch complete\\n at runScoring (score.js:188)",
    metadata: "tenant=marketa; batch=2026-06-18",
  },
  {
    id: "er-11",
    dateTime: "2026-06-18 11:49",
    agentId: "ag-10",
    severity: "WARNING",
    summary: "Desfase horario detectado en reporte.",
    message: "Algunas transacciones llegaron con timezone invalido.",
    stackTrace:
      "TimezoneWarning: fallback UTC\\n at normalizeDate (time.js:42)",
    metadata: "tenant=zencore; source=erp-main",
  },
  {
    id: "er-12",
    dateTime: "2026-06-18 12:03",
    agentId: "ag-5",
    severity: "ERROR",
    summary: "Conflicto de agenda no resuelto automaticamente.",
    message: "Dos eventos de alta prioridad comparten franja horaria.",
    stackTrace: "ScheduleConflictError\\n at resolveConflict (calendar.js:127)",
    metadata: "tenant=orbis; eventPair=9921-9928",
  },
  {
    id: "er-13",
    dateTime: "2026-06-18 12:25",
    agentId: "ag-2",
    severity: "WARNING",
    summary: "Lead duplicado detectado.",
    message: "Se encontraron coincidencias por email y dominio.",
    stackTrace: "DuplicateWarning\\n at mergeLeads (leads.js:211)",
    metadata: "tenant=velocorp; duplicates=4",
  },
  {
    id: "er-14",
    dateTime: "2026-06-18 12:48",
    agentId: "ag-4",
    severity: "INFO",
    summary: "Sincronizacion de metricas completada.",
    message: "Metrica semanal actualizada en dashboard interno.",
    stackTrace: "Info: metrics sync ok\\n at syncMetrics (metrics.js:89)",
    metadata: "tenant=lumen; source=ops-api",
  },
  {
    id: "er-15",
    dateTime: "2026-06-18 13:16",
    agentId: "ag-3",
    severity: "CRITICAL",
    summary: "Caida de worker de analisis documental.",
    message: "El proceso termino por falta de memoria asignada.",
    stackTrace: "FatalError: out of memory\\n at Worker.process (worker.js:54)",
    metadata: "tenant=altavia; pod=doc-analyzer-2",
  },
];
